### ISSUE TITLE
extraVolumeMounts not working in 3.2.0

### ISSUE THREAD

**Issue by angelnu** [nextcloud/helm#296]
Due to https://github.com/nextcloud/helm/commit/1fee95ac23e2a9b1a4568b9444eaa88ef749c422 the `extraVolumeMounts` is ignored. It is missing at https://github.com/nextcloud/helm/blob/1fee95ac23e2a9b1a4568b9444eaa88ef749c422/charts/nextcloud/templates/_helpers.tpl#L210

**Comment by mrtndwrd** [comment]
Running into the same problem here. Seems like the solution is easy, fortunately! Just re-add: 

```
       {{- if .Values.nextcloud.extraVolumeMounts }}
         {{- toYaml .Values.nextcloud.extraVolumeMounts | indent 8 }}
       {{- end }}
```
to the container spec

**Comment by kretzlaff** [comment]
I am the author of the commit that introduced the change. I'll provide a PR to fix this issue asap. Sorry for the inconvenience.
If you add the above snippet to the deployment.yaml it will work.
When you want to add it to the template the " | indent 8" part must be removed otherwise the generated yaml will be invalid.

_helpers.tpl
```
{{- if .Values.nextcloud.extraVolumeMounts }}
{{ toYaml .Values.nextcloud.extraVolumeMounts }}
{{- end }}
```

**Comment by angelnu** [comment]
I just did a PR for that @kretzlaff but the fix is indeed trivial. Thanks for the new feature!
