### ISSUE TITLE
Return git history

### ISSUE THREAD

**Issue by scottrigby** [nextcloud/helm#7]
For a similar example, see this issue https://github.com/goharbor/harbor-helm/issues/48

**Comment by billimek** [comment]
@scottrigby I think I did this properly but before force-pushing to master (which makes me a bit nervous), I'd like to see if you can verify that this sort of commit history looks 'good'?

![image](https://user-images.githubusercontent.com/6393612/91601374-9590f680-e937-11ea-8eb8-c5745f7a4c56.png)

Commit `b878a125f` is the fist one in the new repo, and all prior commits are from the old helm/charts repo.  

One interesting thing I noticed is after following the history-merge instructions, I had to remove some extraneous files from the root of this repo.  It looks like the contents of the old `helm/charts` `stable/nextcloud` directory got dumped into the root of this repo (things like `Chart.yaml`, `.helmignore`, `templates/`, etc).  I had to `git rm` those files and commit that to make it clean (`diff -r --exclude=".git" ...`.

Otherwise, do you think that's good enough before force pushing to master?

**Comment by scottrigby** [comment]
Hey @billimek 👋  I checked out your `merge-git-history` branch, and looks good. But since the Harbor issue I've begun to use https://github.com/newren/git-filter-repo for these kinds of operations. It can help with the path change issue (why it looks like you made the cruft cleanup commit), and also documents a [re-grafting history](https://github.com/newren/git-filter-repo/blob/main/Documentation/converting-from-filter-branch.md#re-grafting-history) use case. 

Luckily there are only 2 forks of this repo so far – and one of them is yours 🙂 – because adding history like this requires force pushing a history change to the main branch so users in the middle of making changes would need to reconcile that. I would say this already looks great 👍 but the above tool might make it even nicer if you want to give it a shot on another branch and see?

**Comment by billimek** [comment]
Thanks @scottrigby!  I felt pretty confident about the original approach and didn't want to puzzle out the newer, better git-filter-repo approach (will likely try that when migrating the unifi chart).

This should be done now.
